// Package grapheme provides Unicode grapheme cluster segmentation (UAX #29
// extended grapheme clusters) and terminal display-width measurement
// (UAX #11 East Asian Width plus UTS #51 emoji data) with zero dependencies,
// backed by generated, committed tables.
//
// It is the Unicode layer beneath golib/tui's cell buffer (ADR-0003 §2.7):
// tui.Graphemes, tui.StringWidth, tui.StringWidthPolicy, and
// Surface.StringWidth are thin wrappers over Clusters, ClusterWidth, and
// StringWidth.
//
// # Segmentation
//
// Clusters implements the UAX #29 extended grapheme cluster rules GB1–GB13
// and GB999: CR LF joining (GB3), control breaking (GB4/GB5), Hangul jamo
// composition (GB6–GB8), Extend/ZWJ/SpacingMark absorption (GB9/GB9a),
// Prepend (GB9b), Extended_Pictographic ZWJ sequences — emoji joins — (GB11),
// and Regional Indicator pairing — flags — (GB12/GB13). Conformance is
// defined as passing every case of the pinned Unicode version's
// GraphemeBreakTest.txt, which the test suite runs from gen/testdata.
//
// Rule GB9c (Indic conjunct clusters via the InCB property) was introduced in
// Unicode 15.1 and is intentionally NOT implemented: this package pins
// Unicode 15.0.0 to match the Go 1.25 standard library's unicode.Version, and
// GB9c does not exist in the 15.0.0 rule set (15.0.0's GraphemeBreakTest.txt
// contains no conjunct cases). Implement GB9c when the pin moves to ≥ 15.1.0;
// the InCB data lives in DerivedCoreProperties.txt, which the generator
// already mirrors.
//
// # Width
//
// The width model is wcwidth-shaped, per cluster (ADR-0003 §2.7): each rune
// is 0, 1, or 2 columns — 0 for C0/C1 controls, combining marks (Mn/Me), and
// default-ignorable code points (which include ZWJ, ZWNJ, and the variation
// selectors); 2 for East Asian Wide/Fullwidth and Emoji_Presentation; 1
// otherwise. A cluster's width is the width of its first non-zero-width
// rune, with overrides: a Regional Indicator pair (flag) is 2, a variation
// selector VS16 (U+FE0F) forces 2, and VS15 (U+FE0E) forces 1. East Asian
// Ambiguous measures 1 by default and 2 when ambiguousWide is set (legacy
// CJK contexts); the public policy surface is tui.WidthPolicy.
//
// # Table provenance and refresh
//
// tables.go is generated by gen/gen.go from Unicode Character Database files
// pinned at the version named in the go:generate line below and mirrored
// under gen/testdata/ (EastAsianWidth.txt, GraphemeBreakProperty.txt,
// emoji-data.txt, DerivedCoreProperties.txt, DerivedGeneralCategory.txt,
// GraphemeBreakTest.txt). The generated header records the SHA-256 of every
// input, so tables are reproducible offline and auditable. No network is
// needed at build, generate, or test time.
//
// Refresh procedure (routine PR on Unicode releases, ~annual):
//
//  1. Bump the version in the go:generate line below.
//  2. go generate ./tui/internal/grapheme (add -download to the gen
//     invocation, or run: go run ./gen -unicode <ver> -download from this
//     directory, to refresh the gen/testdata mirror).
//  3. If the new version is ≥ 15.1.0, implement GB9c (see above) — the
//     conformance suite will fail loudly on the new GraphemeBreakTest.txt
//     conjunct cases until it exists.
//  4. go test ./tui/internal/grapheme/... — conformance and width tests
//     must pass.
//  5. Commit tables.go together with the refreshed mirror, naming the
//     version bump in the commit message.
package grapheme

//go:generate go run ./gen -unicode 15.0.0
