package html_test

import (
	"bytes"
	"strings"
	"testing"

	"github.com/yongjohnlee80/golib/parse/markdown"
	"github.com/yongjohnlee80/golib/parse/markdown/html"
)

// specCase proves one rule of the specification. Rule is the rule's id in rules_test.go; Pos says
// whether the construct forms (true) or a near miss must not form it (false). Cases are written
// from the rule's statement, not copied from the specification's examples.
type specCase struct {
	Rule string
	Pos  bool
	In   string
	Want string
}

func render(t *testing.T, in string) string {
	t.Helper()
	var b bytes.Buffer
	if err := html.Render(&b, markdown.Parse([]byte(in)), html.Unsafe()); err != nil {
		t.Fatal(err)
	}
	return b.String()
}

func runCases(t *testing.T, cases []specCase) {
	t.Helper()
	for _, c := range cases {
		if got := render(t, c.In); got != c.Want {
			t.Errorf("%s (positive=%v)\n in:   %q\n got:  %q\n want: %q", c.Rule, c.Pos, c.In, got, c.Want)
		}
	}
}

var casesPreliminaries = []specCase{
	{"2.1/line-endings", true, "a\r\nb\rc\n", "<p>a\nb\nc</p>\n"},
	{"2.2/tab-stops", true, "\tfoo\n", "<pre><code>foo\n</code></pre>\n"},
	{"2.2/tab-stops", true, "  \tfoo\n", "<pre><code>foo\n</code></pre>\n"},
	{"2.2/tab-stops", false, "   foo\n", "<p>foo</p>\n"},
	{"2.2/tab-in-content-kept", true, "    a\tb\n", "<pre><code>a\tb\n</code></pre>\n"},
	{"2.2/partial-tab-becomes-spaces", true, ">\t\tfoo\n", "<blockquote>\n<pre><code>  foo\n</code></pre>\n</blockquote>\n"},
	{"2.3/nul-replaced", true, "a\x00b\n", "<p>a\uFFFDb</p>\n"},
	{"2.4/backslash-escape", true, "\\*not em\\*\n", "<p>*not em*</p>\n"},
	{"2.4/backslash-escape", false, "\\a\n", "<p>\\a</p>\n"},
	{"2.4/backslash-escape", false, "`\\*`\n", "<p><code>\\*</code></p>\n"},
	{"2.5/entity-reference", true, "&copy; &amp;\n", "<p>© &amp;</p>\n"},
	{"2.5/entity-reference", true, "&#35; &#0;\n", "<p># \uFFFD</p>\n"},
	{"2.5/entity-reference", true, "&#x22;\n", "<p>&quot;</p>\n"},
	{"2.5/entity-reference", false, "&nosuch; &copy\n", "<p>&amp;nosuch; &amp;copy</p>\n"},
	{"2.5/entity-reference", false, "&#12345678;\n", "<p>&amp;#12345678;</p>\n"},
	{"2.5/numeric-reference-range", true, "&#1234567; &#xD800; &#x10FFFF;\n", "<p>\uFFFD \uFFFD \U0010FFFF</p>\n"},
	{"2.5/numeric-reference-range", false, "&#x1000000; &#x;\n", "<p>&amp;#x1000000; &amp;#x;</p>\n"},
	{"2.4/backslash-escape", true, "\\!\\\"\\#\n", "<p>!&quot;#</p>\n"},
	{"2.4/escape-in-destinations", true, "[a](/\\*b)\n", "<p><a href=\"/*b\">a</a></p>\n"},
	{"2.4/escape-in-destinations", false, "<http://a\\b>\n", "<p><a href=\"http://a%5Cb\">http://a\\b</a></p>\n"},
	{"2.4/escaped-ampersand-starts-no-reference", true, "``` \\&amp;\n```\n", "<pre><code class=\"language-&amp;amp;\"></code></pre>\n"},
	{"2.4/escaped-ampersand-starts-no-reference", true, "[a](/\\&#42;)\n", "<p><a href=\"/&amp;#42;\">a</a></p>\n"},
	{"2.4/escaped-ampersand-starts-no-reference", false, "``` &amp;\n```\n", "<pre><code class=\"language-&amp;\"></code></pre>\n"},
	{"2.5/entity-in-destination", true, "[a](/f&ouml;)\n", "<p><a href=\"/f%C3%B6\">a</a></p>\n"},
	{"2.5/entity-in-destination", false, "`&ouml;`\n", "<p><code>&amp;ouml;</code></p>\n"},
	{"2.5/entity-is-not-markup", true, "&#42;foo&#42;\n", "<p>*foo*</p>\n"},
	{"2.5/entity-is-not-markup", false, "*foo*\n", "<p><em>foo</em></p>\n"},
}

var casesLeaf = []specCase{
	{"4.1/thematic-break", true, "***\n---\n___\n", "<hr />\n<hr />\n<hr />\n"},
	{"4.1/thematic-break", true, " - - -\n", "<hr />\n"},
	{"4.1/thematic-break", false, "**\n", "<p>**</p>\n"},
	{"4.1/thematic-break", false, "*-*\n", "<p><em>-</em></p>\n"},
	{"4.2/atx-heading", true, "# a\n###### f\n", "<h1>a</h1>\n<h6>f</h6>\n"},
	{"4.2/atx-heading", true, "#\n", "<h1></h1>\n"},
	{"4.2/atx-heading", false, "####### x\n", "<p>####### x</p>\n"},
	{"4.2/atx-heading", false, "#x\n", "<p>#x</p>\n"},
	{"4.2/closing-sequence", true, "## b ##\n", "<h2>b</h2>\n"},
	{"4.2/closing-sequence", false, "# c#\n", "<h1>c#</h1>\n"},
	{"4.3/setext-heading", true, "A\n===\nB\n---\n", "<h1>A</h1>\n<h2>B</h2>\n"},
	{"4.3/setext-heading", true, "a\nb\n==\n", "<h1>a\nb</h1>\n"},
	{"4.3/setext-heading", false, "A\n= =\n", "<p>A\n= =</p>\n"},
	{"4.3x4.1/setext-before-thematic-break", true, "Foo\n---\n", "<h2>Foo</h2>\n"},
	{"4.3x4.1/setext-before-thematic-break", false, "a\n\n---\n", "<p>a</p>\n<hr />\n"},
	{"4.4/indented-code", true, "    a\n      b\n", "<pre><code>a\n  b\n</code></pre>\n"},
	{"4.4/indented-code", false, "p\n    q\n", "<p>p\nq</p>\n"},
	{"4.4/trailing-blank-lines-dropped", true, "    a\n\n\n", "<pre><code>a\n</code></pre>\n"},
	{"4.5/fenced-code", true, "```\n<\n```\n", "<pre><code>&lt;\n</code></pre>\n"},
	{"4.5/fenced-code", true, "```\nx\n", "<pre><code>x\n</code></pre>\n"},
	{"4.5/fenced-code", false, "``\na\n``\n", "<p><code>a</code></p>\n"},
	{"4.5/info-string", true, "~~~ go x\nf\n~~~\n", "<pre><code class=\"language-go\">f\n</code></pre>\n"},
	{"4.5/info-string", false, "``` a`b\n", "<p>``` a`b</p>\n"},
	{"4.5/closing-fence", true, "````\na\n`````\n", "<pre><code>a\n</code></pre>\n"},
	{"4.5/closing-fence", false, "````\na\n```\n", "<pre><code>a\n```\n</code></pre>\n"},
	{"4.6/html-block-type1", true, "<pre>\n\n*c*\n</pre>\n", "<pre>\n\n*c*\n</pre>\n"},
	{"4.6/html-block-type1", false, "<pref>\n\n*c*\n", "<pref>\n<p><em>c</em></p>\n"},
	{"4.6/html-block-type2", true, "<!-- c -->\n", "<!-- c -->\n"},
	{"4.6/html-block-type2", false, "<!- x ->\n", "<p>&lt;!- x -&gt;</p>\n"},
	{"4.6/html-block-type6", true, "<div>\n*x*\n</div>\n", "<div>\n*x*\n</div>\n"},
	{"4.6/html-block-type6", true, "p\n<div>\n", "<p>p</p>\n<div>\n"},
	{"4.6/html-block-type6", false, "<divs\n", "<p>&lt;divs</p>\n"},
	{"4.6/html-block-type7", true, "<span>\n", "<span>\n"},
	{"4.6/html-block-type7", false, "p\n<span>\n", "<p>p\n<span></p>\n"},
	{"4.7/link-reference-definition", true, "[a]: /u \"t\"\n\n[a]\n", "<p><a href=\"/u\" title=\"t\">a</a></p>\n"},
	{"4.7/link-reference-definition", false, "[a]: /u \"t\" x\n", "<p>[a]: /u &quot;t&quot; x</p>\n"},
	{"4.7/link-reference-definition", false, "[b]\n", "<p>[b]</p>\n"},
	{"4.7/label-matching", true, "[\u1E9E]\n\n[SS]: /u\n", "<p><a href=\"/u\">\u1E9E</a></p>\n"},
	{"4.7/label-matching", true, "[a   B]\n\n[A b]: /u\n", "<p><a href=\"/u\">a   B</a></p>\n"},
	{"4.7/label-matching", false, "[a b]\n\n[ab]: /u\n", "<p>[a b]</p>\n"},
	{"4.7/first-definition-wins", true, "[a]: /1\n[a]: /2\n\n[a]\n", "<p><a href=\"/1\">a</a></p>\n"},
	{"4.8/paragraph-lines", true, "a\n  b\n", "<p>a\nb</p>\n"},
	{"4.9/blank-lines-separate", true, "a\n\n\nb\n", "<p>a</p>\n<p>b</p>\n"},
	{"4.1/interrupts-paragraph", true, "a\n***\nb\n", "<p>a</p>\n<hr />\n<p>b</p>\n"},
	{"4.1/interrupts-paragraph", false, "a\n***x\n", "<p>a\n***x</p>\n"},
	{"4.1/indentation", true, "   ***\n", "<hr />\n"},
	{"4.1/indentation", false, "    ***\n", "<pre><code>***\n</code></pre>\n"},
	{"4.2/atx-heading", true, "# *a*\n", "<h1><em>a</em></h1>\n"},
	{"4.2/indentation", true, "   # a\n", "<h1>a</h1>\n"},
	{"4.2/indentation", false, "    # a\n", "<pre><code># a\n</code></pre>\n"},
	{"4.2/closing-sequence", false, "# a \\#\n", "<h1>a #</h1>\n"},
	{"4.3/underline-indentation", true, "a\n   ==\n", "<h1>a</h1>\n"},
	{"4.3/underline-indentation", false, "a\n    ==\n", "<p>a\n==</p>\n"},
	{"4.4/interior-blank-lines", true, "    a\n\n    b\n", "<pre><code>a\n\nb\n</code></pre>\n"},
	{"4.4/interior-blank-lines", false, "    a\n\nb\n", "<pre><code>a\n</code></pre>\n<p>b</p>\n"},
	{"4.5/info-string", true, "~~~ a`b\nx\n~~~\n", "<pre><code class=\"language-a`b\">x\n</code></pre>\n"},
	{"4.5/fence-indentation", true, "  ```\n  a\n b\n```\n", "<pre><code>a\nb\n</code></pre>\n"},
	{"4.5/fence-indentation", true, "  ```\n    a\n```\n", "<pre><code>  a\n</code></pre>\n"},
	{"4.5/interrupts-paragraph", true, "a\n```\nb\n```\n", "<p>a</p>\n<pre><code>b\n</code></pre>\n"},
	{"4.5/interrupts-paragraph", false, "a\n``\nb\n", "<p>a\n``\nb</p>\n"},
	{"4.5/closing-fence", true, "```\na\n   ```\n", "<pre><code>a\n</code></pre>\n"},
	{"4.5/closing-fence", false, "```\na\n    ```\n", "<pre><code>a\n    ```\n</code></pre>\n"},
	{"4.6/html-block-type1", true, "<PRE>\nx\n</PRE>\n", "<PRE>\nx\n</PRE>\n"},
	{"4.6/html-block-type3", true, "<?php\n\n?>\n", "<?php\n\n?>\n"},
	{"4.6/html-block-type3", false, "\\<?x\n", "<p>&lt;?x</p>\n"},
	{"4.6/html-block-type4", true, "<!DOCTYPE html>\n", "<!DOCTYPE html>\n"},
	{"4.6/html-block-type4", false, "<!1>\n", "<p>&lt;!1&gt;</p>\n"},
	{"4.6/html-block-type5", true, "<![CDATA[\nx\n]]>\n", "<![CDATA[\nx\n]]>\n"},
	{"4.6/html-block-type5", false, "<![CDATA\n", "<p>&lt;![CDATA</p>\n"},
	{"4.6/html-block-type6", true, "<div>\n*a*\n\n*b*\n", "<div>\n*a*\n<p><em>b</em></p>\n"},
	{"4.6/html-block-type7", true, "</span>\n", "</span>\n"},
	{"4.7/link-reference-definition", true, "[a]:\n/u\n'title'\n\n[a]\n", "<p><a href=\"/u\" title=\"title\">a</a></p>\n"},
	{"4.7/at-paragraph-start", true, "[a]: /u\np\n\n[a]\n", "<p>p</p>\n<p><a href=\"/u\">a</a></p>\n"},
	{"4.7/at-paragraph-start", false, "p\n[a]: /u\n\n[a]\n", "<p>p\n[a]: /u</p>\n<p>[a]</p>\n"},
	{"4.7/label-matching", true, "[a\\]b]: /u\n\n[a\\]b]\n", "<p><a href=\"/u\">a]b</a></p>\n"},
	{"4.6/html-block-type7", false, "> a\n<b>\n", "<blockquote>\n<p>a\n<b></p>\n</blockquote>\n"},
	{"4.7x4.3/definitions-then-underline", true, "[r]: /u\n---\n", "<p>---</p>\n"},
	{"4.7x4.3/definitions-then-underline", true, "[r]: /u\n===\n", "<p>===</p>\n"},
	{"4.7x4.3/definitions-then-underline", false, "[r]: /u\na\n---\n", "<h2>a</h2>\n"},
}

var casesContainer = []specCase{
	{"5.1/block-quote", true, "> a\n> b\n", "<blockquote>\n<p>a\nb</p>\n</blockquote>\n"},
	{"5.1/block-quote", false, "\\> a\n", "<p>&gt; a</p>\n"},
	{"5.1/laziness", true, "> a\nb\n", "<blockquote>\n<p>a\nb</p>\n</blockquote>\n"},
	{"5.1/laziness", false, ">     a\n    b\n", "<blockquote>\n<pre><code>a\n</code></pre>\n</blockquote>\n<pre><code>b\n</code></pre>\n"},
	{"5.1/laziness", false, "> a\n---\n", "<blockquote>\n<p>a</p>\n</blockquote>\n<hr />\n"},
	{"5.1x5.2/lazy-line-in-list-in-quote", true, "> - a\nb\n", "<blockquote>\n<ul>\n<li>a\nb</li>\n</ul>\n</blockquote>\n"},
	{"5.1x5.2/lazy-line-in-list-in-quote", false, "> - a\n>\nb\n", "<blockquote>\n<ul>\n<li>a</li>\n</ul>\n</blockquote>\n<p>b</p>\n"},
	{"5.1/blank-ends-quote", true, "> a\n\n> b\n", "<blockquote>\n<p>a</p>\n</blockquote>\n<blockquote>\n<p>b</p>\n</blockquote>\n"},
	{"5.1/blank-ends-quote", false, "> a\n>\n> b\n", "<blockquote>\n<p>a</p>\n<p>b</p>\n</blockquote>\n"},
	{"5.2/list-marker", true, "- a\n- b\n", "<ul>\n<li>a</li>\n<li>b</li>\n</ul>\n"},
	{"5.2/list-marker", true, "3. a\n", "<ol start=\"3\">\n<li>a</li>\n</ol>\n"},
	{"5.2/list-marker", false, "1234567890. a\n", "<p>1234567890. a</p>\n"},
	{"5.2/list-marker", false, "-a\n", "<p>-a</p>\n"},
	{"5.2/list-marker", false, "*\n\n    - x\n", "<ul>\n<li></li>\n</ul>\n<pre><code>- x\n</code></pre>\n"},
	{"5.2/item-content-indent", true, "-   a\n\n    b\n", "<ul>\n<li>\n<p>a</p>\n<p>b</p>\n</li>\n</ul>\n"},
	{"5.2/item-content-indent", true, "-     a\n", "<ul>\n<li>\n<pre><code>a\n</code></pre>\n</li>\n</ul>\n"},
	{"5.2/item-content-indent", false, "- a\n\n b\n", "<ul>\n<li>a</li>\n</ul>\n<p>b</p>\n"},
	{"5.2/interrupt-paragraph", true, "p\n- a\n", "<p>p</p>\n<ul>\n<li>a</li>\n</ul>\n"},
	{"5.2/interrupt-paragraph", false, "p\n-\n", "<h2>p</h2>\n"},
	{"5.2/interrupt-paragraph", false, "p\n2. a\n", "<p>p\n2. a</p>\n"},
	{"5.3/list-continuity", true, "- a\n- b\n", "<ul>\n<li>a</li>\n<li>b</li>\n</ul>\n"},
	{"5.3/list-continuity", false, "- a\n+ b\n", "<ul>\n<li>a</li>\n</ul>\n<ul>\n<li>b</li>\n</ul>\n"},
	{"5.3/loose-tight", true, "- a\n\n- b\n", "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n</ul>\n"},
	{"5.3/loose-tight", false, "- a\n- b\n\n", "<ul>\n<li>a</li>\n<li>b</li>\n</ul>\n"},
	{"5.1/nesting", true, ">> a\n", "<blockquote>\n<blockquote>\n<p>a</p>\n</blockquote>\n</blockquote>\n"},
	{"5.1/nesting", true, "> a\n>> b\n", "<blockquote>\n<p>a</p>\n<blockquote>\n<p>b</p>\n</blockquote>\n</blockquote>\n"},
	{"5.2/list-marker", true, "003. a\n", "<ol start=\"3\">\n<li>a</li>\n</ol>\n"},
	{"5.2/item-starts-blank", true, "-\n  a\n", "<ul>\n<li>a</li>\n</ul>\n"},
	{"5.2/item-starts-blank", false, "-\n\n  a\n", "<ul>\n<li></li>\n</ul>\n<p>a</p>\n"},
	{"5.2/sublist", true, "- a\n  - b\n", "<ul>\n<li>a\n<ul>\n<li>b</li>\n</ul>\n</li>\n</ul>\n"},
	{"5.2/sublist", false, "- a\n - b\n", "<ul>\n<li>a</li>\n<li>b</li>\n</ul>\n"},
	{"5.2/content-column-counts-marker-indent", true, " -  a\n\n    b\n", "<ul>\n<li>\n<p>a</p>\n<p>b</p>\n</li>\n</ul>\n"},
	{"5.2/content-column-counts-marker-indent", false, " -  a\n\n   b\n", "<ul>\n<li>a</li>\n</ul>\n<p>b</p>\n"},
	{"5.2/tab-after-marker", true, "-\ta\n", "<ul>\n<li>a</li>\n</ul>\n"},
	{"5.2/tab-after-marker", true, "-\t\ta\n", "<ul>\n<li>\n<pre><code>  a\n</code></pre>\n</li>\n</ul>\n"},
	{"5.2/tab-after-marker", false, "\t-\ta\n", "<pre><code>-\ta\n</code></pre>\n"},
	{"5.3/start-from-first-item", true, "2. a\n1. b\n", "<ol start=\"2\">\n<li>a</li>\n<li>b</li>\n</ol>\n"},
	{"5.3/list-continuity", true, "2. a\n5. b\n", "<ol start=\"2\">\n<li>a</li>\n<li>b</li>\n</ol>\n"},
	{"5.3/list-continuity", false, "1. a\n2) b\n", "<ol>\n<li>a</li>\n</ol>\n<ol start=\"2\">\n<li>b</li>\n</ol>\n"},
	{"5.3/loose-tight", true, "- a\n\n\n- b\n", "<ul>\n<li>\n<p>a</p>\n</li>\n<li>\n<p>b</p>\n</li>\n</ul>\n"},
}

var casesInline = []specCase{
	{"6.1/code-span", true, "`a`\n", "<p><code>a</code></p>\n"},
	{"6.1/code-span", true, "`a\nb`\n", "<p><code>a b</code></p>\n"},
	{"6.1/code-span", false, "``a`\n", "<p>``a`</p>\n"},
	{"6.1/space-stripping", true, "`` ` ``\n", "<p><code>`</code></p>\n"},
	{"6.1/space-stripping", false, "`  `\n", "<p><code>  </code></p>\n"},
	{"6.2/emphasis", true, "*a* **b** _c_ __d__\n", "<p><em>a</em> <strong>b</strong> <em>c</em> <strong>d</strong></p>\n"},
	{"6.2/emphasis", true, "a*b*c\n", "<p>a<em>b</em>c</p>\n"},
	{"6.2/emphasis", true, "***a***\n", "<p><em><strong>a</strong></em></p>\n"},
	{"6.2/emphasis", false, "a_b_c\n", "<p>a_b_c</p>\n"},
	{"6.2/emphasis", false, "* a*\n", "<ul>\n<li>a*</li>\n</ul>\n"},
	{"6.2/emphasis", false, "a * b *\n", "<p>a * b *</p>\n"},
	{"6.2/rule-of-three", true, "*a**b*\n", "<p><em>a**b</em></p>\n"},
	{"6.2/rule-of-three", false, "*a **b** c*\n", "<p><em>a <strong>b</strong> c</em></p>\n"},
	{"6.3/inline-link", true, "[a](/u \"t\")\n", "<p><a href=\"/u\" title=\"t\">a</a></p>\n"},
	{"6.3/inline-link", true, "[a](<b c>)\n", "<p><a href=\"b%20c\">a</a></p>\n"},
	{"6.3/inline-link", true, "[a]()\n", "<p><a href=\"\">a</a></p>\n"},
	{"6.3/inline-link", false, "[a] (/u)\n", "<p>[a] (/u)</p>\n"},
	{"6.3/links-do-not-nest", true, "[a [b](/2)](/1)\n", "<p>[a <a href=\"/2\">b</a>](/1)</p>\n"},
	{"6.3/links-do-not-nest", false, "![a [b](/2)](/1)\n", "<p><img src=\"/1\" alt=\"a b\" /></p>\n"},
	{"6.3/reference-link", true, "[x][r]\n\n[r]: /u\n", "<p><a href=\"/u\">x</a></p>\n"},
	{"6.3/reference-link", true, "[r][]\n\n[r]: /u\n", "<p><a href=\"/u\">r</a></p>\n"},
	{"6.3/reference-link", false, "[x][nope]\n\n[x]: /u\n", "<p>[x][nope]</p>\n"},
	{"6.3/code-span-precedence", true, "[not `a](/u)`\n", "<p>[not <code>a](/u)</code></p>\n"},
	{"6.3/code-span-precedence", false, "[a `]`](/u)\n", "<p><a href=\"/u\">a <code>]</code></a></p>\n"},
	{"6.4/image", true, "![a *b*](/i.png \"t\")\n", "<p><img src=\"/i.png\" alt=\"a b\" title=\"t\" /></p>\n"},
	{"6.4/image", false, "! [a](/u)\n", "<p>! <a href=\"/u\">a</a></p>\n"},
	{"6.5/autolink", true, "<http://x.y/z>\n", "<p><a href=\"http://x.y/z\">http://x.y/z</a></p>\n"},
	{"6.5/autolink", true, "<a@b.c>\n", "<p><a href=\"mailto:a@b.c\">a@b.c</a></p>\n"},
	{"6.5/autolink", false, "<http://a b>\n", "<p>&lt;http://a b&gt;</p>\n"},
	{"6.6/raw-html", true, "a <b c=\"d\">e</b>\n", "<p>a <b c=\"d\">e</b></p>\n"},
	{"6.6/raw-html", false, "a <1b>\n", "<p>a &lt;1b&gt;</p>\n"},
	{"6.7/hard-break", true, "a  \nb\n", "<p>a<br />\nb</p>\n"},
	{"6.7/hard-break", true, "a\\\nb\n", "<p>a<br />\nb</p>\n"},
	{"6.7/hard-break", false, "a  \n", "<p>a</p>\n"},
	{"6.7/hard-break", false, "a \nb\n", "<p>a\nb</p>\n"},
	{"6.9/text", true, "hello $.;'there\n", "<p>hello $.;'there</p>\n"},
	{"6.2/emphasis", true, "**foo**bar\n", "<p><strong>foo</strong>bar</p>\n"},
	{"6.2/emphasis", false, "__foo__bar\n", "<p>__foo__bar</p>\n"},
	{"6.2/flanking-punctuation", true, "*(*foo*)*\n", "<p><em>(<em>foo</em>)</em></p>\n"},
	{"6.2/flanking-punctuation", false, "a*\"foo\"*\n", "<p>a*&quot;foo&quot;*</p>\n"},
	{"6.2/rule-of-three", true, "*foo**bar**baz*\n", "<p><em>foo<strong>bar</strong>baz</em></p>\n"},
	{"6.2/partial-match", true, "**foo*\n", "<p>*<em>foo</em></p>\n"},
	{"6.2/partial-match", true, "_foo_bar_\n", "<p><em>foo_bar</em></p>\n"},
	{"6.2/partial-match", false, "*foo**\n", "<p><em>foo</em>*</p>\n"},
	{"6.3/inline-link", true, "[*a*](/u)\n", "<p><a href=\"/u\"><em>a</em></a></p>\n"},
	{"6.3/destination-parens", true, "[a](/u(b))\n", "<p><a href=\"/u(b)\">a</a></p>\n"},
	{"6.3/destination-parens", false, "[a](/u(b)\n", "<p>[a](/u(b)</p>\n"},
	{"6.3/destination-paren-nesting-limit", true, "[a](" + strings.Repeat("(", 32) + strings.Repeat(")", 32) + ")\n",
		"<p><a href=\"" + strings.Repeat("(", 32) + strings.Repeat(")", 32) + "\">a</a></p>\n"},
	{"6.3/destination-paren-nesting-limit", false, "[a](" + strings.Repeat("(", 33) + strings.Repeat(")", 33) + ")\n",
		"<p>[a](" + strings.Repeat("(", 33) + strings.Repeat(")", 33) + ")</p>\n"},
	{"6.3/link-title", true, "[a](/u 't') [b](/v (t))\n", "<p><a href=\"/u\" title=\"t\">a</a> <a href=\"/v\" title=\"t\">b</a></p>\n"},
	{"6.3/link-title", false, "[a](/u\"t\")\n", "<p><a href=\"/u%22t%22\">a</a></p>\n"},
	{"6.3/link-before-emphasis", true, "*[a*](/u)\n", "<p>*<a href=\"/u\">a*</a></p>\n"},
	{"6.3/link-before-emphasis", false, "*[a](/u)*\n", "<p><em><a href=\"/u\">a</a></em></p>\n"},
	{"6.5/autolink", true, "<MAILTO:x@y.z>\n", "<p><a href=\"MAILTO:x@y.z\">MAILTO:x@y.z</a></p>\n"},
	{"6.5/autolink", false, "<a:b>\n", "<p>&lt;a:b&gt;</p>\n"},
	{"6.5/autolink-references-decode", true, "<http://a/&#42;&amp;>\n", "<p><a href=\"http://a/*&amp;\">http://a/*&amp;</a></p>\n"},
	{"6.5/autolink-references-decode", false, "<http://a/&nosuch;>\n", "<p><a href=\"http://a/&amp;nosuch;\">http://a/&amp;nosuch;</a></p>\n"},
	{"6.3/inline-link", true, "[a](/u'v)\n", "<p><a href=\"/u&#x27;v\">a</a></p>\n"},
	{"6.6/raw-html", true, "a <!-- b --> c </b>\n", "<p>a <!-- b --> c </b></p>\n"},
	{"6.6/raw-html", false, "a <!-- b\n", "<p>a &lt;!-- b</p>\n"},
	{"6.7/hard-break", true, "*a  \nb*\n", "<p><em>a<br />\nb</em></p>\n"},
	{"6.9/text", true, "a > b & c\n", "<p>a &gt; b &amp; c</p>\n"},
	{"6.7/hard-break", true, "a\t  \nb\n", "<p>a<br />\nb</p>\n"},
	{"6.8/line-end-whitespace-stripped", true, "a \t\nb\n", "<p>a\nb</p>\n"},
	{"6.8/line-end-whitespace-stripped", true, "a  \t\nb\n", "<p>a\nb</p>\n"},
	{"4.8/leading-whitespace-stripped", true, "  a\n   b\n", "<p>a\nb</p>\n"},
	{"4.8/leading-whitespace-stripped", true, "[a]: /u\n\tb\n", "<p>b</p>\n"},
	{"6.2/underscore-after-punctuation", true, "a-_(b)_\n", "<p>a-<em>(b)</em></p>\n"},
	{"6.2/underscore-after-punctuation", false, "a_(b)_\n", "<p>a_(b)_</p>\n"},
	{"6.2/minimal-nesting", true, "****a****\n", "<p><strong><strong>a</strong></strong></p>\n"},
	{"6.2/minimal-nesting", false, "*_a_*\n", "<p><em><em>a</em></em></p>\n"},
	{"6.2/first-closer-wins", true, "*a _b* c_\n", "<p><em>a _b</em> c_</p>\n"},
	{"6.2/first-closer-wins", false, "*a _b_ c*\n", "<p><em>a <em>b</em> c</em></p>\n"},
	{"6.2/shorter-span-wins", true, "**a **b c**\n", "<p>**a <strong>b c</strong></p>\n"},
	{"6.2/shorter-span-wins", false, "**a b c**\n", "<p><strong>a b c</strong></p>\n"},
	{"6.2/code-and-html-bind-tighter", true, "*a `*`*\n", "<p><em>a <code>*</code></em></p>\n"},
	{"6.2/code-and-html-bind-tighter", true, "*a <b title=\"*\">*\n", "<p><em>a <b title=\"*\"></em></p>\n"},
	{"6.2/code-and-html-bind-tighter", false, "*a `b*`\n", "<p>*a <code>b*</code></p>\n"},
	{"6.3/link-text-brackets", true, "[a [b] c](/u)\n", "<p><a href=\"/u\">a [b] c</a></p>\n"},
	{"6.3/link-text-brackets", false, "[a ]b](/u)\n", "<p>[a ]b](/u)</p>\n"},
	{"6.3/inline-before-reference", true, "[a](/i)\n\n[a]: /r\n", "<p><a href=\"/i\">a</a></p>\n"},
	{"6.3/inline-before-reference", false, "[a] (/i)\n\n[a]: /r\n", "<p><a href=\"/r\">a</a> (/i)</p>\n"},
	{"6.3/full-reference-adjacent", true, "[a][b]\n\n[b]: /u\n", "<p><a href=\"/u\">a</a></p>\n"},
	{"6.3/full-reference-adjacent", false, "[a] [b]\n\n[b]: /u\n", "<p>[a] <a href=\"/u\">b</a></p>\n"},
	{"6.5/scheme-length", true, "<ab:c> <" + strings.Repeat("a", 32) + ":c>\n",
		"<p><a href=\"ab:c\">ab:c</a> <a href=\"" + strings.Repeat("a", 32) + ":c\">" + strings.Repeat("a", 32) + ":c</a></p>\n"},
	{"6.5/scheme-length", false, "<" + strings.Repeat("a", 33) + ":c>\n", "<p>&lt;" + strings.Repeat("a", 33) + ":c&gt;</p>\n"},
}

func TestCommonMark(t *testing.T) {
	for name, cases := range map[string][]specCase{
		"preliminaries": casesPreliminaries,
		"leaf":          casesLeaf,
		"container":     casesContainer,
		"inline":        casesInline,
	} {
		t.Run(name, func(t *testing.T) { runCases(t, cases) })
	}
}
